checkpoint:
  path: ''
data:
  seed: 42
model:
  name: whisper_mesonet
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001
  parameters:
    fc1_dim: 1024
    freeze_encoder: true
    frontend_algorithm: []
    input_channels: 1
