checkpoint:
  path: "whisper_mfcc_mesonet/weights.pth"
data:
  seed: 42
model:
  name: whisper_frontend_mesonet
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001
  parameters:
    fc1_dim: 1024
    freeze_encoder: true
    frontend_algorithm:
    - mfcc
    input_channels: 2
